# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Eyetracking_process02.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import time
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QDialog
from selenium import webdriver


class Ui_Dialog(QDialog):

    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(464, 537)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(80, 60, 300, 60))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 150, 300, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 240, 300, 60))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 330, 300, 60))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 420, 300, 60))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.pushButton.clicked.connect(self.open_url1)
        self.pushButton_2.clicked.connect(self.open_url2)
        self.pushButton_3.clicked.connect(self.open_url3)
        self.pushButton_4.clicked.connect(self.open_url4)
        self.pushButton_5.clicked.connect(self.open_url5)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "职位数据图表"))
        self.pushButton.setText(_translate("Dialog", "薪资区间"))
        self.pushButton_2.setText(_translate("Dialog", "经验学历要求情况"))
        self.pushButton_3.setText(_translate("Dialog", "学历要求和薪资情况"))
        self.pushButton_4.setText(_translate("Dialog", "经验要求和薪资情况"))
        self.pushButton_5.setText(_translate("Dialog", "公司福利"))

    def open_url1(self):
        driver = webdriver.Chrome()
        driver.get('file:////E:/BaiduSyncdisk/Python/学校作业/python大作业boss/薪资区间.html')
        driver.set_window_size(1250, 900)
        time.sleep(10)
        driver.close()
        # webbrowser.open('file:////E:/BaiduSyncdisk/Python/学校作业/python大作业boss/薪资区间.html')

    def open_url2(self):
        driver = webdriver.Chrome()
        driver.get('file:////E:/BaiduSyncdisk/Python/学校作业/python大作业boss/经验学历要求情况.html')
        driver.set_window_size(1250, 900)
        time.sleep(10)
        driver.close()

    def open_url3(self):
        driver = webdriver.Chrome()
        driver.get('file:////E:/BaiduSyncdisk/Python/学校作业/python大作业boss/学历要求和薪资情况.html')
        driver.set_window_size(1250, 900)
        time.sleep(7)
        driver.close()

    def open_url4(self):
        driver = webdriver.Chrome()
        driver.get('file:////E:/BaiduSyncdisk/Python/学校作业/python大作业boss/经验要求和薪资情况.html')
        driver.set_window_size(1250, 900)
        time.sleep(7)
        driver.close()

    def open_url5(self):
        driver = webdriver.Chrome()
        driver.get('file:////E:/BaiduSyncdisk/Python/学校作业/python大作业boss/公司福利.html')
        driver.set_window_size(1250, 900)
        time.sleep(6)
        driver.close()
