# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '政策索引.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pymysql
import time
from PyQt5 import QtCore, QtGui, QtWidgets
from selenium import webdriver


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(695, 261)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(80, 110, 531, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(244, 160, 191, 23))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(80, 70, 531, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "http://www.baidu.com"))
        self.pushButton.setText(_translate("Form", "打开网页"))
        self.comboBox.setItemText(0, _translate("Form", "一行"))

    def query(self):
        # 1. 连接数据库，
        conn = pymysql.connect(
            host='192.168.96.128',
            user='root',
            password='123456',
            db='boss',
            charset='utf8',
        )
        cur = conn.cursor()
        sqli = f"select * from policy;"
        result = cur.execute(sqli)
        info = list(cur.fetchall())
        cur.close()
        conn.close()
        return info

    def openurl(self, url):
        driver = webdriver.Chrome()
        driver.get(url)
        driver.set_window_size(1250, 900)
        time.sleep(15)
        driver.close()